<a href="https://colab.research.google.com/github/Pepcoders/Data-Science-February/blob/main/NLP/Spam_Ham_Classifier_Feb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd


In [2]:
messages=pd.read_csv('https://raw.githubusercontent.com/Pepcoders/Data-Science-January/main/NLP/sms',sep='\t',names=['label','message'])

In [3]:
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [4]:
#Data Cleaning and Processing
import nltk 
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/basque_grammars.zip.
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/biocreative_ppi.zip.
[nltk_data]    | Downloadin

True

In [5]:
import re

In [6]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [7]:
ps=PorterStemmer()
corpus=[]

In [10]:
for i in range(0,len(messages)):
  review = re.sub('[^a-zA-Z]', ' ', messages['message'][i])
  review=review.lower()
  review=review.split()


  review=[ps.stem(word) for word in review if word not in stopwords.words('english')]
  review=" ".join(review)
  corpus.append(review)

['sarfaraz','sameer','are','friends']

==> 2nd loop (one-liner function)

        1. sarfaraz  stopword X ==> stemming ==> sarfara

        2. sameer  stopword X ==> stemming ==> samee

        3. are stopword > stemming X

        4. friends stopword X ===> stemming ==> frien

===============JOINING => sarfaa samee are frien 

[sarfaa samee are frien ]===> corpus

In [ ]:
corpus

In [12]:
## Create Bag Of Words Model
## Convert text into numeric data

from sklearn.feature_extraction.text import CountVectorizer

cv=CountVectorizer()

In [14]:
X=cv.fit_transform(corpus).toarray()

In [16]:
X.shape

(5572, 6296)

In [17]:
messages['label']

0        ham
1        ham
2       spam
3        ham
4        ham
        ... 
5567    spam
5568     ham
5569     ham
5570     ham
5571     ham
Name: label, Length: 5572, dtype: object

In [18]:
from sklearn.preprocessing import LabelEncoder

lb=LabelEncoder()

y=lb.fit_transform(messages['label'])

In [19]:
y

array([0, 0, 1, ..., 0, 0, 0])

In [21]:
from sklearn.model_selection import train_test_split


In [22]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [23]:
X_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [24]:
from sklearn.naive_bayes import MultinomialNB , GaussianNB

model1=MultinomialNB()
model2=GaussianNB()

In [25]:
model1.fit(X_train,y_train)

MultinomialNB()

In [26]:
model1.score(X_train,y_train)

0.9921471842046219

In [27]:
model1.score(X_test,y_test)

0.9766816143497757

In [28]:
model2.fit(X_train,y_train)

GaussianNB()

In [31]:
model2.score(X_train,y_train)

0.9169845187345749

In [32]:
model2.score(X_test,y_test)

0.8600896860986547

In [33]:
#### MULTINOMIAL NB IS PERFORMING WELL #####

In [34]:
model1.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0])