<a href="https://colab.research.google.com/github/Pepcoders/Data-Science-February/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])

In [3]:
type(arr)

numpy.ndarray

In [5]:
print(arr.ndim)

1


In [6]:
arr.size

5

In [7]:
arr.dtype

dtype('int64')

In [23]:
arr = np.array([1,2,3,4,5],dtype='uint8')

In [22]:
arr.dtype

dtype('<U21')

In [10]:
arr = np.array([1,2,3,4,5.5])


In [11]:
arr.dtype

dtype('float64')

In [12]:
type(arr[0])

numpy.float64

Time

In [33]:
ll = [1]*100000

In [ ]:
print(ll)

In [35]:
arr = np.ones(100000,dtype='uint8')

In [36]:
%timeit sum(ll)

1000 loops, best of 5: 665 µs per loop


In [37]:
%timeit arr.sum()

10000 loops, best of 5: 112 µs per loop


In [38]:
%timeit sum(arr)

100 loops, best of 5: 14.7 ms per loop


Creating Scratch

In [40]:
np.ones(9,dtype='int32')

array([1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [42]:
np.zeros((5,2),dtype='int32')

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [43]:
np.arange(3,10,2)

array([3, 5, 7, 9])

Slicing

In [44]:
arr = np.arange(10,40,5)

In [45]:
arr

array([10, 15, 20, 25, 30, 35])

In [46]:
arr[2:4]

array([20, 25])

In [47]:
l = [1,2,3,4]
l2 = l[1:3]
print(l)
print(l2)
l2[0] = 1000
print(l)
print(l2)

[1, 2, 3, 4]
[2, 3]
[1, 2, 3, 4]
[1000, 3]


In [48]:
arr = np.array([1,2,3,4])
arr2 = arr[1:3]
print(arr)
print(arr2)
arr2[0] = 1000
print(arr)
print(arr2)

[1 2 3 4]
[2 3]
[   1 1000    3    4]
[1000    3]


In [49]:
arr = np.array([1,2,3,4])
arr2 = arr[1:3].copy()
print(arr)
print(arr2)
arr2[0] = 1000
print(arr)
print(arr2)

[1 2 3 4]
[2 3]
[1 2 3 4]
[1000    3]
