<a href="https://colab.research.google.com/github/Pepcoders/Data-Science-February/blob/main/Tensorflow_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.8.2


==> Tensorflow (Basic Functions)
1. ANN Build
2. How to select number of hidden layers and neurons
3. Keras-Tuner (DL=>Randomized Search CV)
 

In [3]:
import tensorflow as tf
print("TensorFlow version: {}".format(tf.__version__))
print("Keras version: {}".format(tf.keras.__version__))

TensorFlow version: 2.8.2
Keras version: 2.8.0


In [4]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


True

In [5]:
k=tf.constant(42)

In [6]:
k=tf.constant(1, dtype = tf.int64)

In [7]:
k.shape

TensorShape([])

In [8]:
a=tf.constant([[4,2],[9,5]])

In [9]:
b=tf.constant(a)

In [10]:
print(tf.ones(shape=(2,3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [11]:
print(tf.zeros(shape=(3,2)))

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [12]:
a1 = tf.constant([[3,4,5], [3,4,5]])
a2= tf.constant([[1,2,3], [1,2,3]])

c=tf.add(a1,a2)


In [13]:
c

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[4, 6, 8],
       [4, 6, 8]], dtype=int32)>

In [14]:
tf.random.normal(shape=(2,2),mean=0,stddev=1.0)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.57768255,  0.6809504 ],
       [-0.44325253, -0.33938992]], dtype=float32)>

In [15]:
tf.random.uniform(shape=(2,2),minval=0,maxval=10,dtype=tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[8, 5],
       [1, 4]], dtype=int32)>

In [16]:
a=tf.Variable(23)

In [17]:
a

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=23>

In [18]:
a2=tf.Variable([23])

In [19]:
a2

<tf.Variable 'Variable:0' shape=(1,) dtype=int32, numpy=array([23], dtype=int32)>

In [20]:
tensor = tf.Variable([ [ [10., 11., 12.], [13., 14., 15.] ], [ [16., 17., 18.], [19., 20., 21.] ] ]) # tensor variable
print(tensor.shape)

(2, 2, 3)


In [21]:
tensor1 = tf.reshape(tensor,[2,6])

In [22]:
tensor1

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[10., 11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20., 21.]], dtype=float32)>

In [23]:
tensor1.numpy()

array([[10., 11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20., 21.]], dtype=float32)