<a href="https://colab.research.google.com/github/Pepcoders/Data-Science-February/blob/main/Pandas/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

**Series**

1D

In [2]:
A = pd.Series([1,2,3,4])

In [3]:
A

0    1
1    2
2    3
3    4
dtype: int64

In [4]:
A = pd.Series(["Apple","Banana","Mango","Orange"])

In [5]:
A

0     Apple
1    Banana
2     Mango
3    Orange
dtype: object

In [6]:
A = pd.Series([1,2,3,4],index = ['a','b','c','d'])

In [7]:
A

a    1
b    2
c    3
d    4
dtype: int64

In [8]:
print(A.values)

[1 2 3 4]


In [9]:
print(type(A.values))

<class 'numpy.ndarray'>


In [10]:
print(type(A.index))
print(A.index)

<class 'pandas.core.indexes.base.Index'>
Index(['a', 'b', 'c', 'd'], dtype='object')


**Slicing**

implicit iloc [Start:end)

Explicit loc [Start:end]

In [11]:
A

a    1
b    2
c    3
d    4
dtype: int64

In [12]:
A.iloc[0:2]

a    1
b    2
dtype: int64

In [13]:
A.loc['a':'c']

a    1
b    2
c    3
dtype: int64

In [15]:
C = pd.Series([1,2,3,4],index = [1,4,2,7])

In [16]:
C

1    1
4    2
2    3
7    4
dtype: int64

In [17]:
C.iloc[0:3]

1    1
4    2
2    3
dtype: int64

In [18]:
C.loc[1:2]

1    1
4    2
2    3
dtype: int64

In [19]:
C.loc[0:3]

KeyError: ignored

In [20]:
C

1    1
4    2
2    3
7    4
dtype: int64

In [21]:
C.loc[1:5]

KeyError: ignored

In [22]:
C = pd.Series([1,2,3,4,5],index = [1,4,2,7,2])

In [23]:
C

1    1
4    2
2    3
7    4
2    5
dtype: int64

In [24]:
C.loc[1:2]

KeyError: ignored

**Creating from dict**

In [25]:
heightd = {'A': 5.5, 'B':5.8, 'C':6.2}

In [26]:
heightd

{'A': 5.5, 'B': 5.8, 'C': 6.2}

In [27]:
height = pd.Series(heightd)
print(height)

A    5.5
B    5.8
C    6.2
dtype: float64


In [28]:
weightd = {'A': 48, 'B':50, 'C':69}

weight = pd.Series(weightd)
weight

A    48
B    50
C    69
dtype: int64

**DataFrame**

rowindexing -> indexes

column indexing -> column

In [29]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])

In [30]:
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [31]:
print(df.values)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
print(df.index)

RangeIndex(start=0, stop=3, step=1)


In [34]:
df.columns

RangeIndex(start=0, stop=3, step=1)

In [35]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], index = ['r1','r2','r3'],columns = ['c1','c2','c3'])

In [36]:
df

c1  c2  c3
r1   1   2   3
r2   4   5   6
r3   7   8   9

In [39]:
print(height)

A    5.5
B    5.8
C    6.2
dtype: float64


In [38]:
weight

A    48
B    50
C    69
dtype: int64

In [40]:
df = pd.DataFrame({
    'Height':height,
    'Weight':weight
})

In [41]:
df

Height  Weight
A     5.5      48
B     5.8      50
C     6.2      69

In [42]:
print(df.index)
print(df.columns)

Index(['A', 'B', 'C'], dtype='object')
Index(['Height', 'Weight'], dtype='object')


In [43]:
print(df['Height'])

A    5.5
B    5.8
C    6.2
Name: Height, dtype: float64


In [44]:
df

Height  Weight
A     5.5      48
B     5.8      50
C     6.2      69

In [45]:
print(df.loc['B':'C'])

   Height  Weight
B     5.8      50
C     6.2      69


In [46]:
print(df.iloc[1])

Height     5.8
Weight    50.0
Name: B, dtype: float64


**Indexing Slicing**

In [47]:
df

Height  Weight
A     5.5      48
B     5.8      50
C     6.2      69

In [48]:
df['Height']

A    5.5
B    5.8
C    6.2
Name: Height, dtype: float64

In [50]:
df[['Height','Weight']]

Height  Weight
A     5.5      48
B     5.8      50
C     6.2      69

In [51]:
df[[True,False,True]]

Height  Weight
A     5.5      48
C     6.2      69

In [52]:
df[df['Height']>5.5]

Height  Weight
B     5.8      50
C     6.2      69

**Columns Operation**

In [53]:
df

Height  Weight
A     5.5      48
B     5.8      50
C     6.2      69

In [58]:
df['Height_CM'] = df['Height']*30.48

In [59]:
df

Height  Weight  Height_CM
A     5.5      48    167.640
B     5.8      50    176.784
C     6.2      69    188.976

In [60]:
#del df['Height_CM']

df.drop(columns = ['Height_CM'],index='A',inplace = True)

In [61]:
df

Height  Weight
B     5.8      50
C     6.2      69

In [62]:
df = pd.DataFrame({
    'Height': height,
    'Weight': weight,
})
df

Height  Weight
A     5.5      48
B     5.8      50
C     6.2      69

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, A to C
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Height  3 non-null      float64
 1   Weight  3 non-null      int64  
dtypes: float64(1), int64(1)
memory usage: 180.0+ bytes


In [65]:
df.head(2)

Height  Weight
A     5.5      48
B     5.8      50

In [66]:
df.tail(2)

Height  Weight
B     5.8      50
C     6.2      69

In [67]:
df.describe()

Height     Weight
count  3.000000   3.000000
mean   5.833333  55.666667
std    0.351188  11.590226
min    5.500000  48.000000
25%    5.650000  49.000000
50%    5.800000  50.000000
75%    6.000000  59.500000
max    6.200000  69.000000

**Missing Data**

In [68]:
df = pd.DataFrame({
    'Height': {'A': 48, 'C':69},
    'Weight': {'B':5.8, 'C':6.2},
    'Age': {'A': 10, 'B':15, 'C':12}
})
df

Height  Weight  Age
A    48.0     NaN   10
C    69.0     6.2   12
B     NaN     5.8   15

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, A to B
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Height  2 non-null      float64
 1   Weight  2 non-null      float64
 2   Age     3 non-null      int64  
dtypes: float64(2), int64(1)
memory usage: 204.0+ bytes


In [70]:
df = df.dropna(axis=1)

Age
A   10
C   12
B   15

In [71]:
df

Height  Weight  Age
A    48.0     NaN   10
C    69.0     6.2   12
B     NaN     5.8   15

In [72]:
df['Height'].fillna(df['Height'].mean(),inplace=True)

In [73]:
df

Height  Weight  Age
A    48.0     NaN   10
C    69.0     6.2   12
B    58.5     5.8   15

**DataSet**

In [76]:
df = pd.read_csv('https://raw.githubusercontent.com/neylsoncrepalde/projeto_eda_covid/master/covid_19_data.csv')

In [77]:
df

SNo ObservationDate Province/State  Country/Region  \
0          1      01/22/2020          Anhui  Mainland China   
1          2      01/22/2020        Beijing  Mainland China   
2          3      01/22/2020      Chongqing  Mainland China   
3          4      01/22/2020         Fujian  Mainland China   
4          5      01/22/2020          Gansu  Mainland China   
...      ...             ...            ...             ...   
26708  26709      05/19/2020        Wyoming              US   
26709  26710      05/19/2020       Xinjiang  Mainland China   
26710  26711      05/19/2020          Yukon          Canada   
26711  26712      05/19/2020         Yunnan  Mainland China   
26712  26713      05/19/2020       Zhejiang  Mainland China   

               Last Update  Confirmed  Deaths  Recovered  
0          1/22/2020 17:00        1.0     0.0        0.0  
1          1/22/2020 17:00       14.0     0.0        0.0  
2          1/22/2020 17:00        6.0     0.0        0.0  
3          1/22/2020 17:00        1.0     0.0        0.0  
4          1/22/2020 17:00        0.0     0.0        0.0  
...                    ...        ...     ...        ...  
26708  2020-05-20 02:32:19      776.0    10.0        0.0  
26709  2020-05-20 02:32:19       76.0     3.0       73.0  
26710  2020-05-20 02:32:19       11.0     0.0       11.0  
26711  2020-05-20 02:32:19      185.0     2.0      183.0  
26712  2020-05-20 02:32:19     1268.0     1.0     1267.0  

[26713 rows x 8 columns]

In [78]:
df.head()

SNo ObservationDate Province/State  Country/Region      Last Update  \
0    1      01/22/2020          Anhui  Mainland China  1/22/2020 17:00   
1    2      01/22/2020        Beijing  Mainland China  1/22/2020 17:00   
2    3      01/22/2020      Chongqing  Mainland China  1/22/2020 17:00   
3    4      01/22/2020         Fujian  Mainland China  1/22/2020 17:00   
4    5      01/22/2020          Gansu  Mainland China  1/22/2020 17:00   

   Confirmed  Deaths  Recovered  
0        1.0     0.0        0.0  
1       14.0     0.0        0.0  
2        6.0     0.0        0.0  
3        1.0     0.0        0.0  
4        0.0     0.0        0.0

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26713 entries, 0 to 26712
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   SNo              26713 non-null  int64  
 1   ObservationDate  26713 non-null  object 
 2   Province/State   12882 non-null  object 
 3   Country/Region   26713 non-null  object 
 4   Last Update      26713 non-null  object 
 5   Confirmed        26713 non-null  float64
 6   Deaths           26713 non-null  float64
 7   Recovered        26713 non-null  float64
dtypes: float64(3), int64(1), object(4)
memory usage: 1.6+ MB


In [80]:
df.shape

(26713, 8)

In [81]:
df.describe()

SNo      Confirmed        Deaths      Recovered
count  26713.000000   26713.000000  26713.000000   26713.000000
mean   13357.000000    5690.647550    373.353236    1736.979224
std     7711.523207   23417.369124   2214.074387   10864.727709
min        1.000000       0.000000      0.000000       0.000000
25%     6679.000000      18.000000      0.000000       0.000000
50%    13357.000000     192.000000      3.000000       8.000000
75%    20035.000000    1350.000000     28.000000     187.000000
max    26713.000000  352845.000000  35341.000000  289392.000000

In [82]:
df.drop(columns = ['SNo', 'Last Update'], inplace = True)
df

ObservationDate Province/State  Country/Region  Confirmed  Deaths  \
0          01/22/2020          Anhui  Mainland China        1.0     0.0   
1          01/22/2020        Beijing  Mainland China       14.0     0.0   
2          01/22/2020      Chongqing  Mainland China        6.0     0.0   
3          01/22/2020         Fujian  Mainland China        1.0     0.0   
4          01/22/2020          Gansu  Mainland China        0.0     0.0   
...               ...            ...             ...        ...     ...   
26708      05/19/2020        Wyoming              US      776.0    10.0   
26709      05/19/2020       Xinjiang  Mainland China       76.0     3.0   
26710      05/19/2020          Yukon          Canada       11.0     0.0   
26711      05/19/2020         Yunnan  Mainland China      185.0     2.0   
26712      05/19/2020       Zhejiang  Mainland China     1268.0     1.0   

       Recovered  
0            0.0  
1            0.0  
2            0.0  
3            0.0  
4            0.0  
...          ...  
26708        0.0  
26709       73.0  
26710       11.0  
26711      183.0  
26712     1267.0  

[26713 rows x 6 columns]

In [83]:
df.rename(columns= {'Province/State':'State','Country/Region':'Country'},inplace=True)

In [84]:
df

ObservationDate      State         Country  Confirmed  Deaths  Recovered
0          01/22/2020      Anhui  Mainland China        1.0     0.0        0.0
1          01/22/2020    Beijing  Mainland China       14.0     0.0        0.0
2          01/22/2020  Chongqing  Mainland China        6.0     0.0        0.0
3          01/22/2020     Fujian  Mainland China        1.0     0.0        0.0
4          01/22/2020      Gansu  Mainland China        0.0     0.0        0.0
...               ...        ...             ...        ...     ...        ...
26708      05/19/2020    Wyoming              US      776.0    10.0        0.0
26709      05/19/2020   Xinjiang  Mainland China       76.0     3.0       73.0
26710      05/19/2020      Yukon          Canada       11.0     0.0       11.0
26711      05/19/2020     Yunnan  Mainland China      185.0     2.0      183.0
26712      05/19/2020   Zhejiang  Mainland China     1268.0     1.0     1267.0

[26713 rows x 6 columns]

In [86]:
df['ObservationDate'] = pd.to_datetime(df['ObservationDate'])

In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26713 entries, 0 to 26712
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype         
---  ------           --------------  -----         
 0   ObservationDate  26713 non-null  datetime64[ns]
 1   State            12882 non-null  object        
 2   Country          26713 non-null  object        
 3   Confirmed        26713 non-null  float64       
 4   Deaths           26713 non-null  float64       
 5   Recovered        26713 non-null  float64       
dtypes: datetime64[ns](1), float64(3), object(2)
memory usage: 1.2+ MB


In [88]:
df

ObservationDate      State         Country  Confirmed  Deaths  Recovered
0          2020-01-22      Anhui  Mainland China        1.0     0.0        0.0
1          2020-01-22    Beijing  Mainland China       14.0     0.0        0.0
2          2020-01-22  Chongqing  Mainland China        6.0     0.0        0.0
3          2020-01-22     Fujian  Mainland China        1.0     0.0        0.0
4          2020-01-22      Gansu  Mainland China        0.0     0.0        0.0
...               ...        ...             ...        ...     ...        ...
26708      2020-05-19    Wyoming              US      776.0    10.0        0.0
26709      2020-05-19   Xinjiang  Mainland China       76.0     3.0       73.0
26710      2020-05-19      Yukon          Canada       11.0     0.0       11.0
26711      2020-05-19     Yunnan  Mainland China      185.0     2.0      183.0
26712      2020-05-19   Zhejiang  Mainland China     1268.0     1.0     1267.0

[26713 rows x 6 columns]

In [90]:
max = df['Confirmed'].max()
df[df['Confirmed']==max]

ObservationDate     State Country  Confirmed   Deaths  Recovered
26638      2020-05-19  New York      US   352845.0  28558.0        0.0

In [92]:
df

ObservationDate      State         Country  Confirmed  Deaths  Recovered
0          2020-01-22      Anhui  Mainland China        1.0     0.0        0.0
1          2020-01-22    Beijing  Mainland China       14.0     0.0        0.0
2          2020-01-22  Chongqing  Mainland China        6.0     0.0        0.0
3          2020-01-22     Fujian  Mainland China        1.0     0.0        0.0
4          2020-01-22      Gansu  Mainland China        0.0     0.0        0.0
...               ...        ...             ...        ...     ...        ...
26708      2020-05-19    Wyoming              US      776.0    10.0        0.0
26709      2020-05-19   Xinjiang  Mainland China       76.0     3.0       73.0
26710      2020-05-19      Yukon          Canada       11.0     0.0       11.0
26711      2020-05-19     Yunnan  Mainland China      185.0     2.0      183.0
26712      2020-05-19   Zhejiang  Mainland China     1268.0     1.0     1267.0

[26713 rows x 6 columns]

In [93]:
df.groupby('Country').sum()

Confirmed   Deaths  Recovered
Country                                                      
 Azerbaijan                           1.0      0.0        0.0
('St. Martin',)                       2.0      0.0        0.0
Afghanistan                      115615.0   3211.0    13641.0
Albania                           34319.0   1408.0    20212.0
Algeria                          183263.0  19089.0    76184.0
...                                   ...      ...        ...
Western Sahara                      256.0      0.0      144.0
Yemen                              1190.0    190.0       30.0
Zambia                             8987.0    166.0     3102.0
Zimbabwe                           1386.0    171.0      226.0
occupied Palestinian territory       25.0      0.0        0.0

[223 rows x 3 columns]

In [94]:
df.groupby('Country').sum().reset_index()

Country  Confirmed   Deaths  Recovered
0                        Azerbaijan        1.0      0.0        0.0
1                   ('St. Martin',)        2.0      0.0        0.0
2                       Afghanistan   115615.0   3211.0    13641.0
3                           Albania    34319.0   1408.0    20212.0
4                           Algeria   183263.0  19089.0    76184.0
..                              ...        ...      ...        ...
218                  Western Sahara      256.0      0.0      144.0
219                           Yemen     1190.0    190.0       30.0
220                          Zambia     8987.0    166.0     3102.0
221                        Zimbabwe     1386.0    171.0      226.0
222  occupied Palestinian territory       25.0      0.0        0.0

[223 rows x 4 columns]

In [95]:
df

ObservationDate      State         Country  Confirmed  Deaths  Recovered
0          2020-01-22      Anhui  Mainland China        1.0     0.0        0.0
1          2020-01-22    Beijing  Mainland China       14.0     0.0        0.0
2          2020-01-22  Chongqing  Mainland China        6.0     0.0        0.0
3          2020-01-22     Fujian  Mainland China        1.0     0.0        0.0
4          2020-01-22      Gansu  Mainland China        0.0     0.0        0.0
...               ...        ...             ...        ...     ...        ...
26708      2020-05-19    Wyoming              US      776.0    10.0        0.0
26709      2020-05-19   Xinjiang  Mainland China       76.0     3.0       73.0
26710      2020-05-19      Yukon          Canada       11.0     0.0       11.0
26711      2020-05-19     Yunnan  Mainland China      185.0     2.0      183.0
26712      2020-05-19   Zhejiang  Mainland China     1268.0     1.0     1267.0

[26713 rows x 6 columns]

In [96]:
COG = df.groupby(['Country', 'ObservationDate'])[ ['Confirmed', 'Deaths'] ].sum().reset_index()
COG

Country ObservationDate  Confirmed  Deaths
0                          Azerbaijan      2020-02-28        1.0     0.0
1                     ('St. Martin',)      2020-03-10        2.0     0.0
2                         Afghanistan      2020-02-24        1.0     0.0
3                         Afghanistan      2020-02-25        1.0     0.0
4                         Afghanistan      2020-02-26        1.0     0.0
...                               ...             ...        ...     ...
14696  occupied Palestinian territory      2020-03-12        0.0     0.0
14697  occupied Palestinian territory      2020-03-14        0.0     0.0
14698  occupied Palestinian territory      2020-03-15        0.0     0.0
14699  occupied Palestinian territory      2020-03-16        0.0     0.0
14700  occupied Palestinian territory      2020-03-17        0.0     0.0

[14701 rows x 4 columns]