<a href="https://colab.research.google.com/github/Pepcoders/Data-Science-February/blob/main/Pandas/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

**Series**

1D

In [2]:
A = pd.Series([1,2,3,4])

In [3]:
A

0    1
1    2
2    3
3    4
dtype: int64

In [4]:
A = pd.Series(["Apple","Banana","Mango","Orange"])

In [5]:
A

0     Apple
1    Banana
2     Mango
3    Orange
dtype: object

In [6]:
A = pd.Series([1,2,3,4],index = ['a','b','c','d'])

In [7]:
A

a    1
b    2
c    3
d    4
dtype: int64

In [8]:
print(A.values)

[1 2 3 4]


In [9]:
print(type(A.values))

<class 'numpy.ndarray'>


In [10]:
print(type(A.index))
print(A.index)

<class 'pandas.core.indexes.base.Index'>
Index(['a', 'b', 'c', 'd'], dtype='object')


**Slicing**

implicit iloc [Start:end)

Explicit loc [Start:end]

In [11]:
A

a    1
b    2
c    3
d    4
dtype: int64

In [12]:
A.iloc[0:2]

a    1
b    2
dtype: int64

In [13]:
A.loc['a':'c']

a    1
b    2
c    3
dtype: int64

In [15]:
C = pd.Series([1,2,3,4],index = [1,4,2,7])

In [16]:
C

1    1
4    2
2    3
7    4
dtype: int64

In [17]:
C.iloc[0:3]

1    1
4    2
2    3
dtype: int64

In [18]:
C.loc[1:2]

1    1
4    2
2    3
dtype: int64

In [19]:
C.loc[0:3]

KeyError: ignored

In [20]:
C

1    1
4    2
2    3
7    4
dtype: int64

In [21]:
C.loc[1:5]

KeyError: ignored

In [22]:
C = pd.Series([1,2,3,4,5],index = [1,4,2,7,2])

In [23]:
C

1    1
4    2
2    3
7    4
2    5
dtype: int64

In [24]:
C.loc[1:2]

KeyError: ignored

**Creating from dict**

In [25]:
heightd = {'A': 5.5, 'B':5.8, 'C':6.2}

In [26]:
heightd

{'A': 5.5, 'B': 5.8, 'C': 6.2}

In [27]:
height = pd.Series(heightd)
print(height)

A    5.5
B    5.8
C    6.2
dtype: float64


In [28]:
weightd = {'A': 48, 'B':50, 'C':69}

weight = pd.Series(weightd)
weight

A    48
B    50
C    69
dtype: int64

**DataFrame**

rowindexing -> indexes

column indexing -> column

In [29]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])

In [30]:
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [31]:
print(df.values)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
print(df.index)

RangeIndex(start=0, stop=3, step=1)


In [34]:
df.columns

RangeIndex(start=0, stop=3, step=1)

In [35]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], index = ['r1','r2','r3'],columns = ['c1','c2','c3'])

In [36]:
df

c1  c2  c3
r1   1   2   3
r2   4   5   6
r3   7   8   9

In [39]:
print(height)

A    5.5
B    5.8
C    6.2
dtype: float64


In [38]:
weight

A    48
B    50
C    69
dtype: int64

In [40]:
df = pd.DataFrame({
    'Height':height,
    'Weight':weight
})

In [41]:
df

Height  Weight
A     5.5      48
B     5.8      50
C     6.2      69

In [42]:
print(df.index)
print(df.columns)

Index(['A', 'B', 'C'], dtype='object')
Index(['Height', 'Weight'], dtype='object')


In [43]:
print(df['Height'])

A    5.5
B    5.8
C    6.2
Name: Height, dtype: float64
